# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cityprimarypollutantitem',
            name='pollutant',
            field=models.CharField(choices=[('co', 'CO/1h'), ('no2', 'NO2/1h'), ('o3', 'O3/1h'), ('o3_8h', 'O3/8h'), ('pm10', 'PM10/1h'), ('pm2_5', 'PM2.5/1h'), ('so2', 'SO2/1h')], max_length=5),
        ),
        migrations.AlterField(
            model_name='estimatedcityprimarypollutantitem',
            name='pollutant',
            field=models.CharField(choices=[('co', 'CO/1h'), ('no2', 'NO2/1h'), ('o3', 'O3/1h'), ('o3_8h', 'O3/8h'), ('pm10', 'PM10/1h'), ('pm2_5', 'PM2.5/1h'), ('so2', 'SO2/1h')], max_length=5),
        ),
        migrations.AlterField(
            model_name='estimatedstationprimarypollutantitem',
            name='pollutant',
            field=models.CharField(choices=[('co', 'CO/1h'), ('no2', 'NO2/1h'), ('o3', 'O3/1h'), ('o3_8h', 'O3/8h'), ('pm10', 'PM10/1h'), ('pm2_5', 'PM2.5/1h'), ('so2', 'SO2/1h')], max_length=5),
        ),
        migrations.AlterField(
            model_name='stationprimarypollutantitem',
            name='pollutant',
            field=models.CharField(choices=[('co', 'CO/1h'), ('no2', 'NO2/1h'), ('o3', 'O3/1h'), ('o3_8h', 'O3/8h'), ('pm10', 'PM10/1h'), ('pm2_5', 'PM2.5/1h'), ('so2', 'SO2/1h')], max_length=5),
        ),
    ]
