# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airquality', '0002_auto_20160514_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityrecord',
            options={'get_latest_by': 'update_dtm'},
        ),
        migrations.AlterModelOptions(
            name='stationrecord',
            options={'get_latest_by': 'city_record__update_dtm'},
        ),
        migrations.AddField(
            model_name='cityrecord',
            name='aqhi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='estimatedcityrecord',
            name='aqhi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='estimatedstationrecord',
            name='aqhi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stationrecord',
            name='aqhi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
